version: '3'
services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../deployment/local/backend/Dockerfile
    container_name: backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../deployment/local/frontend/Dockerfile
    container_name: frontend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - '80:3000'

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=game-directory"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
